[patch.crates-io]
# Nats with the tcp stream timeout fix: CAS-1192
nats = { git = "https://github.com/openebs/nats.rs", rev="main_fixes" }

[profile.dev]
panic = "abort"

[workspace]
members = [
	"jsonrpc",
	"libnvme-rs",
	"mayastor",
	"mbus-api",
	"rpc",
	"sysfs",
	"composer",
	"spdk-rs",
]
